[build]
  base = "client"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--include=dev"

[context.production.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
